#!/bin/sh

crv="P-256"
sig="ES256"
enc="ECDH-ES+A128KW"

function mktmpl() {
    echo -n { \"kty\": \"EC\",
    echo -n   \"crv\": \"$1\",
    echo -n   \"key_ops\": [ \"tang.derive\", \"tang.recover\" ] }
}

while getopts "d:c:" opt; do
    case $opt in
        d)  dir=$OPTARG;;
        c)  case $OPTARG in
                P-256) crv="P-256"; sig="ES256"; enc="ECDH-ES+A128KW";;
                P-384) crv="P-384"; sig="ES384"; enc="ECDH-ES+A192KW";;
                P-521) crv="P-521"; sig="ES512"; enc="ECDH-ES+A256KW";;
		*) echo "Unknown curve: $OPTARG!" >&2; exit 1;;
            esac;;
        *) echo "Unknown argument: $opt!" >&2; exit 1;;
    esac
done

jose gen \
    -t "{ \"alg\": \"$sig\" }" \
    -t "{ \"alg\": \"$enc\" }" \
    -t "`mktmpl $crv`"
